# Generated by Django 4.1.7 on 2023-03-04 14:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='sisuser',
            name='user_type',
            field=models.CharField(choices=[('Student', 'STUDENT'), ('Instructor', 'INSTRUCTOR'), ('Admin', 'ADMIN'), ('Other Staff', 'OTHER STAFF')], default=1, max_length=30),
            preserve_default=False,
        ),
    ]
