# Generated by Django 4.1.7 on 2023-03-04 18:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_alter_sisuser_user_type'),
    ]

    operations = [
        migrations.AddField(
            model_name='sisuser',
            name='first_name',
            field=models.CharField(default='Nigus', max_length=50),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='sisuser',
            name='last_name',
            field=models.CharField(default='Solomon', max_length=50),
            preserve_default=False,
        ),
    ]
